### ISSUE TITLE
Consider supporting multiple timestamp sources in n delete-packages action

### ISSUE THREAD

**Issue by iaingalloway** [iaingalloway/devcontainers#1]
```yaml
  timestamp-source:
    description: >
      Source of the timestamp to use for retention
    required: true
    default: updated_at
    enum:
      - updated_at
      - created_at
```
